"use client";

import { useState, useTransition } from "react";
import { createTherapyPlanAction, logTherapySessionAction } from "@/app/actions/therapy";
import { Button } from "@/components/ui/button";

type Child = { id: string; name: string }; type Plan = { id: string; childId: string; therapyType: string; status: string; child: Child };
export function TherapyManager({ profileChildren, plans }: { profileChildren: Child[]; plans: Plan[] }) {
  const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const submitPlan = (data: FormData) => startTransition(async () => { const r = await createTherapyPlanAction({ childId: String(data.get("childId")), therapyType: String(data.get("therapyType")), description: String(data.get("description")), startDate: new Date(String(data.get("startDate"))) }); setMessage(r.error ?? r.success ?? ""); });
  const submitSession = (data: FormData) => startTransition(async () => { const r = await logTherapySessionAction({ therapyPlanId: String(data.get("therapyPlanId")), sessionDate: new Date(String(data.get("sessionDate"))), duration: Number(data.get("duration")), improvementScore: Number(data.get("improvementScore")), notes: String(data.get("notes") || "") }); setMessage(r.error ?? r.success ?? ""); });
  const select = (name: string, values: { value: string; label: string }[]) => <select name={name} required className="h-10 rounded-md border border-input bg-background px-3 text-sm">{values.map((v) => <option key={v.value} value={v.value}>{v.label}</option>)}</select>;
  return <div className="grid gap-8 lg:grid-cols-2"><form action={submitPlan} className="space-y-3 rounded-xl border p-5"><h2 className="font-semibold">Create therapy plan</h2>{select("childId", profileChildren.map((c) => ({ value: c.id, label: c.name })))}<input name="therapyType" required placeholder="Therapy type (e.g. Speech)" className="h-10 w-full rounded-md border px-3 text-sm" /><textarea name="description" required placeholder="Goals and plan details" className="min-h-24 w-full rounded-md border p-3 text-sm" /><input name="startDate" type="date" required className="h-10 rounded-md border px-3 text-sm" /><Button disabled={pending} type="submit">Create plan</Button></form><form action={submitSession} className="space-y-3 rounded-xl border p-5"><h2 className="font-semibold">Log therapy session</h2>{select("therapyPlanId", plans.map((p) => ({ value: p.id, label: `${p.child.name} — ${p.therapyType}` })))}<input name="sessionDate" type="date" required className="h-10 rounded-md border px-3 text-sm" /><input name="duration" type="number" min="1" required placeholder="Duration (minutes)" className="h-10 w-full rounded-md border px-3 text-sm" /><input name="improvementScore" type="number" min="1" max="10" required placeholder="Improvement score (1–10)" className="h-10 w-full rounded-md border px-3 text-sm" /><textarea name="notes" placeholder="Notes (optional)" className="min-h-20 w-full rounded-md border p-3 text-sm" /><Button disabled={pending || plans.length === 0} type="submit">Log session</Button></form>{message && <p className="lg:col-span-2 text-sm text-primary">{message}</p>}</div>;
}
